# >>> AUTOGEN: BYTECODEMAPPER CI GHA SMOKE HARDEN BEGIN
name: Smoke

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch:

concurrency:
  group: smoke-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # >>> AUTOGEN: BYTECODEMAPPER CI GHA SMOKE SKIP FIXTURES BEGIN
  preflight:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      missing: ${{ steps.check.outputs.missing }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check fixture jars exist
        id: check
        run: |
          set -e
          miss=0
          for f in data/weeks/osrs-170.jar data/weeks/osrs-171.jar; do
            if [ ! -f "$f" ]; then
              echo "Missing: $f"
              miss=1
            fi
          done
          echo "missing=$miss" >> $GITHUB_OUTPUT

      - name: Summarize skip (when missing)
        if: steps.check.outputs.missing == '1'
        run: |
          echo "## Smoke skipped" >> "$GITHUB_STEP_SUMMARY"
          echo "- Missing fixture jars under \`data/weeks/\`" >> "$GITHUB_STEP_SUMMARY"
          echo "- This is normal on forks/partial clones" >> "$GITHUB_STEP_SUMMARY"
  # >>> AUTOGEN: BYTECODEMAPPER CI GHA SMOKE SKIP FIXTURES END

  smoke:
    needs: preflight
    if: needs.preflight.outputs.missing != '1'
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 8 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "8"
          cache: gradle

      - name: Show Java version (expect 1.8)
        run: |
          set -eux
          java -version

      - name: Gradle wrapper permissions
        run: chmod +x ./gradlew

      - name: Assert wrapper distributionUrl contains 6.9.4
        run: |
          set -eux
          cat gradle/wrapper/gradle-wrapper.properties
          grep -E "distributionUrl=.*6\.9\.4" gradle/wrapper/gradle-wrapper.properties

      - name: Create CI init script to prove JVM & props
        run: |
          cat > ci-init.gradle <<'EOF'
          println "[CI] env JAVA_HOME=" + System.getenv("JAVA_HOME")
          println "[CI] sysprop org.gradle.java.home=" + System.getProperty("org.gradle.java.home")
          println "[CI] sysprop java.home=" + System.getProperty("java.home")
          EOF

      # >>> AUTOGEN: BYTECODEMAPPER CI GHA SMOKE JVM ARGS BEGIN
      - name: Gradle version (expect 6.9.4) with CI Java override
        run: |
          set -eux
          GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx2g -Dorg.gradle.logging.level=lifecycle"
          ./gradlew -I ci-init.gradle -Dorg.gradle.java.home="$JAVA_HOME" -v | tee gradle-version.txt
          grep -E "^Gradle 6\.9\.4$" gradle-version.txt

      - name: Smoke (deterministic) with CI Java override
        env:
          GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx2g -Dorg.gradle.logging.level=lifecycle"
        run: ./gradlew -Dorg.gradle.java.home="$JAVA_HOME" :mapper-cli:smoke --no-daemon
      # >>> AUTOGEN: BYTECODEMAPPER CI GHA SMOKE JVM ARGS END

      - name: Show hashes
        run: |
          set -eux
          for f in \
            mapper-cli/build/smoke/m1.tiny \
            mapper-cli/build/smoke/m2.tiny \
            mapper-cli/build/smoke/remap-tiny-a.jar \
            mapper-cli/build/smoke/remap-tiny-b.jar \
            mapper-cli/build/smoke/remap-asm-a.jar \
            mapper-cli/build/smoke/remap-asm-b.jar \
            mapper-cli/build/smoke/metrics1.json \
            mapper-cli/build/smoke/metrics2.json ; do
            [ -f "$f" ] && sha256sum "$f" || true
          done

      - name: Upload smoke artifacts (7-day retention)
        uses: actions/upload-artifact@v4
        with:
          name: smoke-artifacts
          retention-days: 7
          path: |
            ci-init.gradle
            gradle-version.txt
            mapper-cli/build/smoke/m1.tiny
            mapper-cli/build/smoke/m2.tiny
            mapper-cli/build/smoke/norm1.txt
            mapper-cli/build/smoke/norm2.txt
            mapper-cli/build/smoke/remap-tiny-a.jar
            mapper-cli/build/smoke/remap-tiny-b.jar
            mapper-cli/build/smoke/remap-asm-a.jar
            mapper-cli/build/smoke/remap-asm-b.jar
            mapper-cli/build/smoke/metrics1.json
            mapper-cli/build/smoke/metrics2.json

      - name: Job summary
        run: |
          {
            echo "## BytecodeMapper Smoke"
            echo ""
            echo "- Java: \`$(java -version 2>&1 | head -n1)\`"
            echo "- Gradle:"; head -n1 gradle-version.txt
            echo "- Wrapper:"; grep distributionUrl gradle/wrapper/gradle-wrapper.properties | sed 's/^/- /'
            echo ""
            echo "Hashes (pairs should match):"
            for f in mapper-cli/build/smoke/m1.tiny mapper-cli/build/smoke/m2.tiny \
                     mapper-cli/build/smoke/remap-tiny-a.jar mapper-cli/build/smoke/remap-tiny-b.jar \
                     mapper-cli/build/smoke/remap-asm-a.jar mapper-cli/build/smoke/remap-asm-b.jar \
                     mapper-cli/build/smoke/metrics1.json mapper-cli/build/smoke/metrics2.json; do
              if [ -f "$f" ]; then
                echo "  - $(sha256sum \"$f\")"
              fi
            done
          } >> "$GITHUB_STEP_SUMMARY"
# >>> AUTOGEN: BYTECODEMAPPER CI GHA SMOKE HARDEN END
