# >>> AUTOGEN: BYTECODEMAPPER CI GHA SMOKE ASSERT BEGIN
name: Smoke

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch:

concurrency:
  group: smoke-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 8 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "8"
          cache: gradle

      - name: Show Java version
        run: |
          set -eux
          java -version

      - name: Gradle wrapper permissions
        run: chmod +x ./gradlew

      - name: Gradle version (expect 6.9.4) and assert
        run: |
          set -eux
          ./gradlew -v | tee gradle-version.txt
          echo "---- Raw gradle -v ----"
          cat gradle-version.txt
          echo "---- Asserting Gradle 6.9.4 ----"
          grep -E "^Gradle 6\.9\.4$" gradle-version.txt

      - name: Smoke (deterministic)
        run: ./gradlew :mapper-cli:smoke --no-daemon -Dorg.gradle.jvmargs="-Xmx2g"

      - name: Show hashes
        run: |
          set -eux
          for f in \
            mapper-cli/build/smoke/m1.tiny \
            mapper-cli/build/smoke/m2.tiny \
            mapper-cli/build/smoke/remap-tiny-a.jar \
            mapper-cli/build/smoke/remap-tiny-b.jar \
            mapper-cli/build/smoke/remap-asm-a.jar \
            mapper-cli/build/smoke/remap-asm-b.jar \
            mapper-cli/build/smoke/metrics1.json \
            mapper-cli/build/smoke/metrics2.json ; do
            [ -f "$f" ] && sha256sum "$f" || true
          done

      - name: Upload smoke artifacts
        uses: actions/upload-artifact@v4
        with:
          name: smoke-artifacts
          path: |
            gradle-version.txt
            mapper-cli/build/smoke/m1.tiny
            mapper-cli/build/smoke/m2.tiny
            mapper-cli/build/smoke/norm1.txt
            mapper-cli/build/smoke/norm2.txt
            mapper-cli/build/smoke/remap-tiny-a.jar
            mapper-cli/build/smoke/remap-tiny-b.jar
            mapper-cli/build/smoke/remap-asm-a.jar
            mapper-cli/build/smoke/remap-asm-b.jar
            mapper-cli/build/smoke/metrics1.json
            mapper-cli/build/smoke/metrics2.json
# >>> AUTOGEN: BYTECODEMAPPER CI GHA SMOKE ASSERT END
