# >>> AUTOGEN: BYTECODEMAPPER CI GHA SMOKE HARDEN BEGIN
name: Smoke

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch:

concurrency:
  group: smoke-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # >>> AUTOGEN: BYTECODEMAPPER CI GHA SMOKE SKIP FIXTURES BEGIN
  preflight:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      missing: ${{ steps.check.outputs.missing }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check fixture jars exist
        id: check
        run: |
          set -e
          miss=0
          for f in data/weeks/osrs-170.jar data/weeks/osrs-171.jar; do
            if [ ! -f "$f" ]; then
              echo "Missing: $f"
              miss=1
            fi
          done
          echo "missing=$miss" >> $GITHUB_OUTPUT

      - name: Summarize skip (when missing)
        if: steps.check.outputs.missing == '1'
        run: |
          echo "## Smoke skipped" >> "$GITHUB_STEP_SUMMARY"
          echo "- Missing fixture jars under \`data/weeks/\`" >> "$GITHUB_STEP_SUMMARY"
          echo "- This is normal on forks/partial clones" >> "$GITHUB_STEP_SUMMARY"
  # >>> AUTOGEN: BYTECODEMAPPER CI GHA SMOKE SKIP FIXTURES END

  smoke:
    needs: preflight
    if: needs.preflight.outputs.missing != '1'
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 8 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "8"
          cache: gradle

      - name: Show Java version (expect 1.8)
        run: |
          set -eux
          java -version

      - name: Gradle wrapper permissions
        run: chmod +x ./gradlew

      - name: Assert wrapper distributionUrl contains 6.9.4
        run: |
          set -eux
          cat gradle/wrapper/gradle-wrapper.properties
          grep -E "distributionUrl=.*6\.9\.4" gradle/wrapper/gradle-wrapper.properties

      - name: Create CI init script to prove JVM & props
        run: |
          cat > ci-init.gradle <<'EOF'
          println "[CI] env JAVA_HOME=" + System.getenv("JAVA_HOME")
          println "[CI] sysprop org.gradle.java.home=" + System.getProperty("org.gradle.java.home")
          println "[CI] sysprop java.home=" + System.getProperty("java.home")
          EOF

      # >>> AUTOGEN: BYTECODEMAPPER CI GHA SMOKE JVM ARGS BEGIN
      - name: Gradle version (expect 6.9.4) with CI Java override
        run: |
          set -eux
          GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx2g -Dorg.gradle.logging.level=lifecycle"
          ./gradlew -I ci-init.gradle -Dorg.gradle.java.home="$JAVA_HOME" -v | tee gradle-version.txt
          grep -E "^Gradle 6\.9\.4$" gradle-version.txt

      - name: Smoke (deterministic) with CI Java override
        env:
          GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx2g -Dorg.gradle.logging.level=lifecycle"
        run: ./gradlew -Dorg.gradle.java.home="$JAVA_HOME" :mapper-cli:smoke --no-daemon
      # >>> AUTOGEN: BYTECODEMAPPER CI GHA SMOKE JVM ARGS END

      - name: Show hashes
        run: |
          set -eux
          for f in \
            mapper-cli/build/smoke/m1.tiny \
            mapper-cli/build/smoke/m2.tiny \
            mapper-cli/build/smoke/remap-tiny-a.jar \
            mapper-cli/build/smoke/remap-tiny-b.jar \
            mapper-cli/build/smoke/remap-asm-a.jar \
            mapper-cli/build/smoke/remap-asm-b.jar \
            mapper-cli/build/smoke/metrics1.json \
            mapper-cli/build/smoke/metrics2.json ; do
            [ -f "$f" ] && sha256sum "$f" || true
          done

      - name: Upload smoke artifacts (7-day retention)
        uses: actions/upload-artifact@v4
        with:
          name: smoke-artifacts
          retention-days: 7
          path: |
            ci-init.gradle
            gradle-version.txt
            mapper-cli/build/smoke/m1.tiny
            mapper-cli/build/smoke/m2.tiny
            mapper-cli/build/smoke/norm1.txt
            mapper-cli/build/smoke/norm2.txt
            mapper-cli/build/smoke/remap-tiny-a.jar
            mapper-cli/build/smoke/remap-tiny-b.jar
            mapper-cli/build/smoke/remap-asm-a.jar
            mapper-cli/build/smoke/remap-asm-b.jar
            mapper-cli/build/smoke/metrics1.json
            mapper-cli/build/smoke/metrics2.json

      - name: Job summary
        run: |
          {
            echo "## BytecodeMapper Smoke"
            echo ""
            echo "- Java: \`$(java -version 2>&1 | head -n1)\`"
            echo "- Gradle:"; head -n1 gradle-version.txt
            echo "- Wrapper:"; grep distributionUrl gradle/wrapper/gradle-wrapper.properties | sed 's/^/- /'
            echo ""
            echo "Hashes (pairs should match):"
            for f in mapper-cli/build/smoke/m1.tiny mapper-cli/build/smoke/m2.tiny \
                     mapper-cli/build/smoke/remap-tiny-a.jar mapper-cli/build/smoke/remap-tiny-b.jar \
                     mapper-cli/build/smoke/remap-asm-a.jar mapper-cli/build/smoke/remap-asm-b.jar \
                     mapper-cli/build/smoke/metrics1.json mapper-cli/build/smoke/metrics2.json; do
              if [ -f "$f" ]; then
                echo "  - $(sha256sum \"$f\")"
              fi
            done
          } >> "$GITHUB_STEP_SUMMARY"
# >>> AUTOGEN: BYTECODEMAPPER CI GHA SMOKE WINDOWS BEGIN
  smoke_windows:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 8 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "8"
          cache: gradle

      - name: Show Java version (expect 1.8)
        shell: pwsh
        run: |
          $PSVersionTable.PSVersion
          java -version

      - name: Assert wrapper distributionUrl contains 6.9.4
        shell: pwsh
        run: |
          Get-Content gradle/wrapper/gradle-wrapper.properties | Write-Host
          (Get-Content gradle/wrapper/gradle-wrapper.properties) -match "6\.9\.4" | Out-Null
          if (-not $?) { throw "Wrapper distributionUrl must contain 6.9.4" }

      - name: "Preflight: check fixture jars"
        id: preflight_win
        shell: pwsh
        run: |
          $missing = 0
          $paths = @("data/weeks/osrs-170.jar","data/weeks/osrs-171.jar")
          foreach ($p in $paths) {
            if (-not (Test-Path $p)) {
              Write-Host "Missing: $p"
              $missing = 1
            }
          }
          echo "missing=$missing" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding ascii -Append

      - name: Summarize skip (Windows)
        if: steps.preflight_win.outputs.missing == '1'
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "## Smoke (Windows) skipped"
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "- Missing fixture jars under \`data/weeks\`"
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "- This is normal on forks/partial clones"

      - name: Stop early (skip job)
        if: steps.preflight_win.outputs.missing == '1'
        shell: pwsh
        run: exit 0

      - name: Create CI init script to prove JVM & props
        shell: pwsh
        run: |
          @"
          println "[CI][WIN] env JAVA_HOME=" + System.getenv("JAVA_HOME")
          println "[CI][WIN] sysprop org.gradle.java.home=" + System.getProperty("org.gradle.java.home")
          println "[CI][WIN] sysprop java.home=" + System.getProperty("java.home")
          "@ | Out-File -FilePath ci-init.gradle -Encoding ascii

      # >>> AUTOGEN: BYTECODEMAPPER CI GHA SMOKE WINDOWS JAVA_HOME NEUTRALIZE BEGIN
      - name: Neutralize local org.gradle.java.home and export ORG_GRADLE_JAVA_HOME
        shell: pwsh
        run: |
          # Ensure any repo-local override doesn't leak into CI
          if (Test-Path 'gradle.properties') {
            Write-Host '[WIN][CI] Neutralizing org.gradle.java.home in gradle.properties'
            $raw = Get-Content gradle.properties -Raw
            $patched = $raw -replace '^(?im)\s*org\.gradle\.java\.home\s*=.*$', '# CI neutralized org.gradle.java.home (uses JAVA_HOME)'
            if ($patched -ne $raw) {
              $patched | Set-Content gradle.properties -Encoding ascii
            }
          }
          # Belt-and-suspenders: also set env var recognized by Gradle
          $env:ORG_GRADLE_JAVA_HOME = $env:JAVA_HOME
          Write-Host "[WIN][CI] JAVA_HOME=$env:JAVA_HOME"
          Write-Host "[WIN][CI] ORG_GRADLE_JAVA_HOME=$env:ORG_GRADLE_JAVA_HOME"
      # >>> AUTOGEN: BYTECODEMAPPER CI GHA SMOKE WINDOWS JAVA_HOME NEUTRALIZE END

      - name: Gradle version (expect 6.9.4) with CI Java override
        shell: pwsh
        run: |
          ./gradlew.bat -I ci-init.gradle -Dorg.gradle.java.home="$env:JAVA_HOME" -v | Tee-Object -FilePath gradle-version-win.txt
          if (-not (Select-String -Path gradle-version-win.txt -Pattern "^Gradle 6\.9\.4$")) { throw "Expected Gradle 6.9.4" }

      - name: Smoke (deterministic) with CI Java override
        shell: pwsh
        run: |
          ./gradlew.bat -Dorg.gradle.java.home="$env:JAVA_HOME" :mapper-cli:smoke --no-daemon -Dorg.gradle.jvmargs="-Xmx2g"

      - name: Show hashes (certutil)
        shell: pwsh
        continue-on-error: true
        run: |
          $files = @(
            "mapper-cli/build/smoke/m1.tiny",
            "mapper-cli/build/smoke/m2.tiny",
            "mapper-cli/build/smoke/remap-tiny-a.jar",
            "mapper-cli/build/smoke/remap-tiny-b.jar",
            "mapper-cli/build/smoke/remap-asm-a.jar",
            "mapper-cli/build/smoke/remap-asm-b.jar",
            "mapper-cli/build/smoke/metrics1.json",
            "mapper-cli/build/smoke/metrics2.json"
          )
          foreach ($f in $files) {
            if (Test-Path $f) {
              Write-Host "---- $f"
              certutil -hashfile $f SHA256
            }
          }

      - name: Upload smoke artifacts (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: smoke-artifacts-windows
          retention-days: 7
          path: |
            ci-init.gradle
            gradle-version-win.txt
            mapper-cli/build/smoke/m1.tiny
            mapper-cli/build/smoke/m2.tiny
            mapper-cli/build/smoke/norm1.txt
            mapper-cli/build/smoke/norm2.txt
            mapper-cli/build/smoke/remap-tiny-a.jar
            mapper-cli/build/smoke/remap-tiny-b.jar
            mapper-cli/build/smoke/remap-asm-a.jar
            mapper-cli/build/smoke/remap-asm-b.jar
            mapper-cli/build/smoke/metrics1.json
            mapper-cli/build/smoke/metrics2.json

      - name: Job summary (Windows)
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "## BytecodeMapper Smoke (Windows)"
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value ""
          $jv = (java -version) 2>&1 | Select-Object -First 1
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value ("- Java: `"${jv}`"")
          $gv = Get-Content gradle-version-win.txt | Select-Object -First 1
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value ("- Gradle: ${gv}")
          $wrap = Get-Content gradle/wrapper/gradle-wrapper.properties | Select-String "distributionUrl"
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value ("- Wrapper: {0}" -f $wrap)
# >>> AUTOGEN: BYTECODEMAPPER CI GHA SMOKE WINDOWS END
# >>> AUTOGEN: BYTECODEMAPPER CI GHA SMOKE HARDEN END
